export type StatusType = "Active" | "Archive" | "Completed";
import { Group } from "../types/group";

export const initialGroups: Group[] = [
  {
    id: 1,
    name: "Group A",
    course: "Math",
    teacher: "John Doe",
    days: "Odd days",
    room: "101",
    students: 10,
    status: "Active",
    tags: ["New"],
    startDate: "2025-09-15",
    endDate: "2026-05-15",
    lessonStartTime: "09:00",
    branch: "YA IELTS Campus",
    price: 400000,
    roomCapacity: 30,
  },
  {
    id: 2,
    name: "Group B",
    course: "English",
    teacher: "Jane Smith",
    days: "Even days",
    room: "102",
    students: 8,
    status: "Active",
    tags: ["Popular"],
    startDate: "2025-09-15",
    endDate: "2026-05-15",
    lessonStartTime: "11:00",
    branch: "YA Grammar Campus",
    price: 300000,
    roomCapacity: 25,
  },
  {
    id: 3,
    name: "Group C",
    course: "Physics",
    teacher: "Michael Brown",
    days: "Odd days",
    room: "103",
    students: 12,
    status: "Archive",
    tags: [],
    startDate: "2025-09-15",
    endDate: "2026-05-15",
    lessonStartTime: "14:00",
    branch: "YA Uzbekistan Massivi",
    price: 400000,
    roomCapacity: 20,
  },
  {
    id: 4,
    name: "Group D",
    course: "IELTS",
    teacher: "Michael Brown",
    days: "Even days",
    room: "103",
    students: 12,
    status: "Completed",
    tags: ["VIP"],
    startDate: "2025-09-15",
    endDate: "2026-05-15",
    lessonStartTime: "14:00",
    branch: "YA IELTS Campus",
    price: 500000,
    roomCapacity: 10,
  },
];