// scheduleData.ts
import { ScheduleEvent } from "../types/dashboardTypes";

export const ROOMS = [
  "1-Xona",
  "3-xona",
  "4-xona",
  "5-xona",
  "6-xona",
  "7-xona",
];

export const EVENTS: ScheduleEvent[] = [
  // ─── ODD days ─────────────────────────────────────────────────────────────
  {
    id: "o1",
    room: "1-Xona",
    start: 14 * 60,
    duration: 90,
    groupName: "IELTS JUNIOR",
    courseName: "IELTS Maksuda Abraykulova",
    teacher: "Maksuda Abraykulova",
    dateRange: "15 sep—31 jul",
    students: 18,
    maxStudents: 18,
    color: "#a78bfa",
    days: ["odd"],
  },
  {
    id: "o2",
    room: "1-Xona",
    start: 16 * 60,
    duration: 90,
    groupName: "Score Boosters",
    courseName: "IELTS Maksuda Abraykulova",
    teacher: "Maksuda Abraykulova",
    dateRange: "1 nov—1 dec",
    students: 17,
    maxStudents: 20,
    color: "#a78bfa",
    days: ["odd"],
  },
  {
    id: "o3",
    room: "3-xona",
    start: 14 * 60,
    duration: 90,
    groupName: "Learning Legends",
    courseName: "Speaking Course Toshmirza Jumaev",
    teacher: "Toshmirza Jumaev",
    dateRange: "1 may—1 jul",
    students: 23,
    maxStudents: 25,
    color: "#34d399",
    days: ["odd"],
  },
  {
    id: "o4",
    room: "3-xona",
    start: 16 * 60,
    duration: 90,
    groupName: "Cobandence",
    courseName: "IELTS Toshmirza Jumaev",
    teacher: "Toshmirza Jumaev",
    dateRange: "19 sep—1 sep",
    students: 22,
    maxStudents: 22,
    color: "#a78bfa",
    days: ["odd"],
  },
  {
    id: "o5",
    room: "4-xona",
    start: 14 * 60,
    duration: 90,
    groupName: "Upgraders",
    courseName: "IELTS Shahzoda Safarova",
    teacher: "Shahzoda Safarova",
    dateRange: "16 sep—1 aug",
    students: 14,
    maxStudents: 16,
    color: "#a78bfa",
    days: ["odd"],
  },
  {
    id: "o6",
    room: "4-xona",
    start: 16 * 60,
    duration: 90,
    groupName: "Fluency Fusion",
    courseName: "IELTS Shahzoda Safarova",
    teacher: "Shahzoda Safarova",
    dateRange: "1 jan—1 sep",
    students: 14,
    maxStudents: 16,
    color: "#a78bfa",
    days: ["odd"],
  },
  {
    id: "o7",
    room: "5-xona",
    start: 8 * 60 + 30,
    duration: 90,
    groupName: "Frozen group",
    courseName: "IELTS Ugilbeka Abdullaeva",
    teacher: "Ugilbeka Abdullaeva",
    dateRange: "1 nov—1 jul",
    students: 5,
    maxStudents: 30,
    color: "#fb923c",
    tag: "Frozen group",
    tagColor: "#6b7280",
    days: ["odd"],
  },
  {
    id: "o8",
    room: "5-xona",
    start: 11 * 60,
    duration: 90,
    groupName: "English Planet",
    courseName: "KIDS English Pardayev Jahongir",
    teacher: "Pardayev Jahongir",
    dateRange: "15 apr—30 sep",
    students: 17,
    maxStudents: 17,
    color: "#34d399",
    days: ["odd"],
  },
  {
    id: "o9",
    room: "5-xona",
    start: 14 * 60,
    duration: 90,
    groupName: "Linguo Sphere",
    courseName: "IELTS Ugilbeka Abdullaeva",
    teacher: "Ugilbeka Abdullaeva",
    dateRange: "9 oct—10 jun",
    students: 15,
    maxStudents: 20,
    color: "#a78bfa",
    days: ["odd"],
  },
  {
    id: "o10",
    room: "5-xona",
    start: 16 * 60,
    duration: 90,
    groupName: "Goal Rushers",
    courseName: "IELTS Ugilbeka Abdullaeva",
    teacher: "Ugilbeka Abdullaeva",
    dateRange: "5 jan—5 sep",
    students: 15,
    maxStudents: 20,
    color: "#a78bfa",
    days: ["odd"],
  },
  {
    id: "o11",
    room: "6-xona",
    start: 16 * 60,
    duration: 90,
    groupName: "yangi guruh",
    courseName: "Tarix Avazov Jahongir",
    teacher: "Avazov Jahongir",
    dateRange: "20 may—20 jan",
    students: 5,
    maxStudents: 30,
    color: "#fb923c",
    tag: "new 8 days",
    tagColor: "#22c55e",
    days: ["odd"],
  },
  {
    id: "o12",
    room: "7-xona",
    start: 11 * 60,
    duration: 90,
    groupName: "Little Numbers",
    courseName: "Math for kids G'ulomjon",
    teacher: "G'ulomjon",
    dateRange: "1 sep—1 jun",
    students: 12,
    maxStudents: 15,
    color: "#34d399",
    days: ["odd"],
  },
  {
    id: "o13",
    room: "7-xona",
    start: 14 * 60,
    duration: 90,
    groupName: "한국어 초급",
    courseName: "Koreys tili Pardayev Jahongir",
    teacher: "Pardayev Jahongir",
    dateRange: "1 oct—1 apr",
    students: 10,
    maxStudents: 15,
    color: "#f87171",
    days: ["odd"],
  },
  {
    id: "o14",
    room: "7-xona",
    start: 16 * 60,
    duration: 90,
    groupName: "Math Masters",
    courseName: "Matematika G'ulomjon",
    teacher: "G'ulomjon",
    dateRange: "1 sep—1 jun",
    students: 13,
    maxStudents: 15,
    color: "#34d399",
    days: ["odd"],
  },

  // ─── EVEN days ────────────────────────────────────────────────────────────
  {
    id: "e1",
    room: "1-Xona",
    start: 9 * 60,
    duration: 90,
    groupName: "Pioneers",
    courseName: "IELTS Maksuda Abraykulova",
    teacher: "Maksuda Abraykulova",
    dateRange: "1 sep—1 jun",
    students: 20,
    maxStudents: 20,
    color: "#a78bfa",
    days: ["even"],
  },
  {
    id: "e2",
    room: "1-Xona",
    start: 15 * 60,
    duration: 90,
    groupName: "Top Scorers",
    courseName: "IELTS Maksuda Abraykulova",
    teacher: "Maksuda Abraykulova",
    dateRange: "1 oct—1 may",
    students: 16,
    maxStudents: 20,
    color: "#a78bfa",
    days: ["even"],
  },
  {
    id: "e3",
    room: "3-xona",
    start: 10 * 60,
    duration: 90,
    groupName: "English Stars",
    courseName: "General English Toshmirza",
    teacher: "Toshmirza Jumaev",
    dateRange: "15 sep—15 jun",
    students: 18,
    maxStudents: 20,
    color: "#34d399",
    days: ["even"],
  },
  {
    id: "e4",
    room: "3-xona",
    start: 14 * 60,
    duration: 90,
    groupName: "Talkers",
    courseName: "Speaking Course Toshmirza",
    teacher: "Toshmirza Jumaev",
    dateRange: "1 nov—1 aug",
    students: 19,
    maxStudents: 22,
    color: "#34d399",
    days: ["even"],
  },
  {
    id: "e5",
    room: "4-xona",
    start: 9 * 60,
    duration: 90,
    groupName: "Band 7 Club",
    courseName: "IELTS Shahzoda Safarova",
    teacher: "Shahzoda Safarova",
    dateRange: "1 sep—1 jun",
    students: 15,
    maxStudents: 16,
    color: "#a78bfa",
    days: ["even"],
  },
  {
    id: "e6",
    room: "5-xona",
    start: 11 * 60,
    duration: 90,
    groupName: "Junior Coders",
    courseName: "IT Kids Ugilbeka",
    teacher: "Ugilbeka Abdullaeva",
    dateRange: "1 oct—1 apr",
    students: 12,
    maxStudents: 15,
    color: "#38bdf8",
    days: ["even"],
  },
  {
    id: "e7",
    room: "5-xona",
    start: 15 * 60,
    duration: 90,
    groupName: "Advanced IELTS",
    courseName: "IELTS Ugilbeka Abdullaeva",
    teacher: "Ugilbeka Abdullaeva",
    dateRange: "1 jan—1 sep",
    students: 14,
    maxStudents: 18,
    color: "#a78bfa",
    days: ["even"],
  },
  {
    id: "e8",
    room: "6-xona",
    start: 10 * 60,
    duration: 90,
    groupName: "History Hub",
    courseName: "Tarix Avazov Jahongir",
    teacher: "Avazov Jahongir",
    dateRange: "1 sep—1 jun",
    students: 17,
    maxStudents: 20,
    color: "#fb923c",
    days: ["even"],
  },
  {
    id: "e9",
    room: "7-xona",
    start: 9 * 60,
    duration: 90,
    groupName: "Math Wizards",
    courseName: "Matematika G'ulomjon",
    teacher: "G'ulomjon",
    dateRange: "1 sep—1 jun",
    students: 14,
    maxStudents: 15,
    color: "#34d399",
    days: ["even"],
  },
  {
    id: "e10",
    room: "7-xona",
    start: 15 * 60,
    duration: 90,
    groupName: "Korean B1",
    courseName: "Koreys tili Pardayev Jahongir",
    teacher: "Pardayev Jahongir",
    dateRange: "1 mar—1 dec",
    students: 9,
    maxStudents: 15,
    color: "#f87171",
    days: ["even"],
  },

  // ─── OTHER ────────────────────────────────────────────────────────────────
  {
    id: "ot1",
    room: "1-Xona",
    start: 10 * 60,
    duration: 120,
    groupName: "Weekend IELTS",
    courseName: "IELTS Maksuda Abraykulova",
    teacher: "Maksuda Abraykulova",
    dateRange: "1 sep—1 jun",
    students: 22,
    maxStudents: 25,
    color: "#a78bfa",
    days: ["other"],
  },
  {
    id: "ot2",
    room: "3-xona",
    start: 11 * 60,
    duration: 120,
    groupName: "Speaking Club",
    courseName: "Free Speaking Toshmirza",
    teacher: "Toshmirza Jumaev",
    dateRange: "Every saturday",
    students: 30,
    maxStudents: 30,
    color: "#34d399",
    days: ["other"],
  },
  {
    id: "ot3",
    room: "5-xona",
    start: 13 * 60,
    duration: 120,
    groupName: "Mock Exam",
    courseName: "IELTS Mock Test",
    teacher: "Various",
    dateRange: "Sundays",
    students: 40,
    maxStudents: 40,
    color: "#f87171",
    days: ["other"],
  },
  {
    id: "ot4",
    room: "7-xona",
    start: 9 * 60,
    duration: 120,
    groupName: "Math Olympiad",
    courseName: "Olimpiada tayyorlov",
    teacher: "G'ulomjon",
    dateRange: "Saturdays",
    students: 20,
    maxStudents: 20,
    color: "#fb923c",
    days: ["other"],
  },
];
